const { FileWatcher } = require("../")
new FileWatcher('./logs/errors.log')
.on('update', () => console.log('The file has been changed'))
.on('warning', console.warn)
.on('error', console.error)
.watch()
